sudo: false
language: php

notifications:
  on_success: never
  on_failure: change
  email: false

env:
  global:
    - PATH=~/.composer/vendor/bin:vendor/bin:$PATH
  matrix:
    - WP_PROJECT_TYPE=plugin WP_VERSION=latest WP_MULTISITE=0 WP_TEST_URL=http://localhost:12000 WP_TEST_USER=test WP_TEST_USER_PASS=test

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache: bundler

before_script:
  # Increase PHP Memory
  - echo "memory_limit=2048M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  
  # Speed up build time by disabling Xdebug.
  # https://johnblackbourn.com/reducing-travis-ci-build-times-for-wordpress-projects/
  # https://twitter.com/kelunik/status/954242454676475904
  - if [ "$TRAVIS_PHP_VERSION" != "5.6" ]; then phpenv config-rm xdebug.ini || echo 'No xdebug config.'; fi

  # Install composer packages before trying to activate themes or plugins
  - composer self-update
  - composer install
  - phpenv rehash

  # Reconfigure PHPUnit Testing for Travis CI using older version
  # https://core.trac.wordpress.org/ticket/43218
  # https://make.wordpress.org/core/handbook/testing/automated-testing/phpunit/#running-the-test-suite
  - wget https://phar.phpunit.de/phpunit-6.5.phar
  - chmod +x phpunit-6.5.phar
  - sudo mv phpunit-6.5.phar /usr/local/bin/phpunit
  - phpunit --version

  # Install Wordpress testing suite and run wordpress
  - git clone https://github.com/koconder/wordpress-test-template wp-tests
  - bash wp-tests/bin/install-wp-tests.sh test root '' localhost $WP_VERSION

  # Test Wordpress is Loading Fine
  - curl -i http://localhost:12000

script:
  # Run PHP Unit and Wordpress Standards Tests
  #- phpcs --standard=WordPress ./**/*.php
  - phpunit --coverage-clover=coverage.xml
  
  # Run rspec tests
  - cd wp-tests/spec && bundle exec rspec baseline.rb

  # Syntax check all php files and fail for any error text in STDERR
  - '! find . -type f -name "*.php" -exec php -d error_reporting=32767 -l {} \; 2>&1 >&- | grep "^"'

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
  - bash <(curl -s https://codecov.io/bash)