sudo: false
language: php

notifications:
  on_success: never
  on_failure: change
  email: false

env: WP_PROJECT_TYPE=plugin WP_VERSION=latest WP_MULTISITE=0 WP_TEST_URL=http://localhost:12000 WP_TEST_USER=test WP_TEST_USER_PASS=test

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm
    - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

cache: bundler

before_script:
  # Get home directory
  - testslocation="$PWD"

  # Install composer packages before trying to activate themes or plugins
  # - composer install

  # Install Wordpress testing suite and run wordpress
  - git clone https://github.com/Koodimonni/wordpress-test-template wp-tests
  - bash wp-tests/bin/install-wp-tests.sh test root '' localhost $WP_VERSION

  # Test wordpress
  - curl -i http://localhost:12000

  # Install gems for rspec tests and run
  - gem install bundler
  - bundle install --gemfile=$PWD/wp-tests/tests-rspec/Gemfile

script:
  #- phpcs --standard=WordPress ./**/*.php
  - phpunit --coverage-clover=coverage.xml
  - bundle exec rspec $PWD/wp-tests/tests-rspec/*.rb

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml